### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by VincentChen1212** [Kisogawa/PasswordList#1]
Hi,
Can I know what kind of this project license (MIT or ??), I love this project, and it is useful to me.

Thanks

**Comment by Kisogawa** [comment]
Hi

Thank you for your love!
Added MIT license notation.

commit: 391a04772c705b3c49969759c1333fa0549d05ae

**Comment by VincentChen1212** [comment]
Hi
I am so so so happy to hear this
Thank you very very very much
